# Generated by Django 5.0.3 on 2024-03-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='proveedor',
            new_name='pv_id',
        ),
    ]
